### ISSUE TITLE
Set up database, ORM, and sample API endpoint

### ISSUE THREAD

**Issue by mxc-maggiechen** [xusandrew/cs-348-project#3]
Completing this requirement from project milestone 0:

_Source code for your “hello world” type of simple database-drive applications with your sample database (e.g. the application allows user to connect to the database, to select some rows from a table, etc.) This just ensures you have (installed and) tested the database systems and simple application code on school servers or your own machines for your interested applications._

**Comment by xusandrew** [comment]
- [x] postgres running with docker compose
- [x] prisma client setup in next connected to postgres instance

**Comment by xusandrew** [comment]
Also:

update README.txt to describe how to create and load your sample database to your chosen platform.
You don’t have to use the datasets described in the report. Toy datasets (e.g. a single table) can
be used.

**Comment by xusandrew** [comment]
ticket requirements changed
